In [3]:
import numpy as np

# creating a numpy array

In [4]:
arr1 = np.array([1,2,3,4,5,6,7,8])

arr2 = np.arange(10,20)

arr3 = np.linspace(0,1,5)

In [5]:
print(arr1)

print(arr2)

print(arr3)

[1 2 3 4 5 6 7 8]
[10 11 12 13 14 15 16 17 18 19]
[0.   0.25 0.5  0.75 1.  ]


# Indexing and sliceing

In [6]:
print(arr1[2])

3


In [7]:
print(arr1[3:6])

[4 5 6]


# array operation

In [8]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

res = arr3 + arr4

print(res)

[5 7 9]


# Reshapeing arrays

In [9]:
arr5 = np.array([1,2,3,4,5,6])


res = arr5.reshape(2,3)

print(res)

[[1 2 3]
 [4 5 6]]


# Array concatination

In [10]:
con = np.concatenate((arr1,arr2))
print(con)

[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19]


# Aggregating data

In [11]:
arr1 = np.array([1,2,3,4,5,6,45,67,34])

mean_val = np.mean(arr1)
print(mean_val)

18.555555555555557


# filter data

In [12]:
arr2 = np.array([10,21,5,6,34,56,23])

filter_data = arr2[arr2 > 15]

print(filter_data)

[21 34 56 23]


# sorting arrays

In [13]:
arr1 = np.array([10,21,5,6,34,56,23])

sorted_arr = np.sort(arr1)
print(sorted_arr)

[ 5  6 10 21 23 34 56]


# Unique Values / frequency

In [15]:
arr1 = np.array([10,15,21,54,12,15,15,15,10])

unique_values , unique_counts = np.unique(arr1,return_counts=True)

print(unique_values)
print(unique_counts)

[10 12 15 21 54]
[2 1 4 1 1]


# Vectorized Operations

In [17]:
arr1 = np.array([10,15,21,54,12,15,15,15,10])

vec_res = arr1 *2

print(vec_res)

[ 20  30  42 108  24  30  30  30  20]
